#!/usr/bin/env bash

if [ -d ".venv" ]; then
    source .venv/bin/activate
fi

echo "Look for changes..."
files=`git status --porcelain | wc -l`
if [ ${files} == 0 ] ; then
    echo "OK"
else
    echo "FAIL"
    git status
    exit 1
fi

.githooks/pre-commit || { echo "FAIL"; exit 1; }
