#!/usr/bin/env bash

python_files="moire/ tests/"

echo "Checking code format with Ruff..."
if ! ruff format --check ${python_files}; then
    ruff format --diff --color ${python_files}
    echo "FAIL"
    exit 1
fi

echo "Checking types with ty..."
if ! ty check; then
    echo "FAIL"
    exit 1
fi

echo "Linting with Ruff..."
if ! ruff check; then
    echo "FAIL"
    exit 1
fi

echo "Run pytest..."
pytest -v || { echo "FAIL"; exit 1; }

echo "OK"
